
edit_db = {
	"hey sae": "hey sae",
	"heisei": "hey sae",
	"delete": "delete",
	"exit": "exit",
	"copy": "copy",
	"paste": "paste",
	"highlight": "highlight",
	"high light": "highlight",
	"back": "back",
	"forward": "forward",
	"up": "up",
	"down": "down",
	"left": "left",
	"right": "right",
	"previous": "previous",
	"line": "line",
	"top": "top",
	"bottom": "bottom",
	"middle": "middle",
	"center": "middle",
	"first": "first",
	"second": "second",
	"last": "last",
	"return": "enter",
	"enter": "enter",
	"new line": "enter",
	"newline": "enter",
	"zero" : "0",
    "one" : "1",
    "two": "2",
    "three": "3",
    "four" : "4",
    "five" : "5",
    "six" : "6",
    "seven" : "7",
    "eight" : "8",
    "nine" : "9",
	"colon" : ":",
	"comma" : ",",
    "common" : ",",
	"quote" : '"',
    "underscore" : "_",
    "under score" : "_",
    "sub" : "[",
    "end sub" : "]",
    "period" : ".",
	"dot": ".",
	"semi colon": ";",
	"semicolon": ";",
	"slash": "/",
	"forward slash": "/",
	"forwardslash": "/",
	"backslash": "\\",
	"back slash": "\\",
	"star": "*",
	"hash": "#",
	"pound": "!",
	"at": "@",
	"tilde": "~",
	"dollar": "$",
	"carrot": "^",
	"percent": "%",
	"ampersand": "&",
	"left paren": "(",
	"right paren": ")",
	"dash": "-",
	"minus": "-",
	"equals": "=",
	"equal": "=",
	"plus": "+",
	"l curly": "{",
	"r curly": "}",
	"verticle bar": "|",
	"verticlebar": "|",
	"question": "?",
	"less than": "<",
	"greater than": ">",
	"escape": "esc",
	"esc": "esc",
	"upper": "shift",
}
